SELECT DATE_FORMAT(O.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, O.PRODUCT_ID, O.USER_ID, O.SALES_AMOUNT FROM ONLINE_SALE O
WHERE (YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '03')
UNION 
SELECT DATE_FORMAT(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT FROM OFFLINE_SALE F
WHERE (YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '03')
# SELECT  FROM ONLINE_SALE O  JOIN OFFLINE_SALE F ON O.PRODUCT_ID = F.PRODUCT_ID
# WHERE (YEAR(O.SALES_DATE) = '2022' AND MONTH(O.SALES_DATE) = '03') OR
# (YEAR(F.SALES_DATE) = '2022' AND MONTH(F.SALES_DATE) = '03')
# GROUP BY 1, 2
ORDER BY 1, 2, 3