SELECT CASE 
WHEN MONTH(DIFFERENTIATION_DATE) = '01' OR MONTH(DIFFERENTIATION_DATE) = '02' OR MONTH(DIFFERENTIATION_DATE) = '03' THEN '1Q'
WHEN MONTH(DIFFERENTIATION_DATE) = '04' OR MONTH(DIFFERENTIATION_DATE) = '05' OR MONTH(DIFFERENTIATION_DATE) = '06' THEN '2Q'
WHEN MONTH(DIFFERENTIATION_DATE) = '07' OR MONTH(DIFFERENTIATION_DATE) = '08' OR MONTH(DIFFERENTIATION_DATE) = '09' THEN '3Q'
ELSE '4Q' END QUARTER
, COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER