SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT P JOIN FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = '2022' AND MONTH(O.PRODUCE_DATE) = '05'
GROUP BY PRODUCT_NAME
ORDER BY 3 DESC, 1 