SELECT B.APNT_NO, A.PT_NAME, B.PT_NO, B.MCDP_CD, C.DR_NAME, B.APNT_YMD
FROM PATIENT A JOIN APPOINTMENT B ON A.PT_NO = B.PT_NO
JOIN DOCTOR C ON C.DR_ID = B.MDDR_ID
WHERE B.APNT_CNCL_YMD IS NULL AND C.MCDP_CD = 'CS'
AND DATE_FORMAT(B.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY 6