# SELECT E.EMP_NO, E.EMP_NAME, AS GRADE, AS BONUS FROM HR_EMPLOYEES E JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO

SELECT E.EMP_NO, E.EMP_NAME, G.GRADE, CASE
WHEN G.GRADE = 'S' THEN E.SAL * 0.2
WHEN G.GRADE = 'A' THEN E.SAL * 0.15
WHEN G.GRADE = 'B' THEN E.SAL * 0.1
ELSE 0
END BONUS FROM HR_EMPLOYEES E
JOIN (
SELECT EMP_NO, CASE 
WHEN SUM(SCORE) / 2 >= 96 THEN 'S' 
WHEN SUM(SCORE) / 2 >= 90 THEN 'A'
WHEN SUM(SCORE) / 2 >= 80 THEN 'B'
ELSE 'C' END GRADE FROM HR_GRADE
GROUP BY EMP_NO
    ) AS G 
ON E.EMP_NO = G.EMP_NO
ORDER BY 1
