SELECT CASE
WHEN YEAR(START_DATE) = '2022' AND MONTH(START_DATE) = '08' THEN '08'
WHEN YEAR(START_DATE) = '2022' AND MONTH(START_DATE) = '09' THEN '09'
WHEN YEAR(START_DATE) = '2022' AND MONTH(START_DATE) = '10' THEN '10'
END MONTH , CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY CAR_ID
HAVING COUNT(*) >= 5
    )
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC