SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
WHERE SKILL_CODE & (
SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'C#') > 1
OR SKILL_CODE & (
SELECT CODE FROM SKILLCODES WHERE NAME LIKE 'Python') > 1
ORDER BY 1