SELECT ID, FISH_NAME, LENGTH
FROM FISH_NAME_INFO N JOIN FISH_INFO I ON N.FISH_TYPE = I.FISH_TYPE
WHERE I.FISH_TYPE IN (
SELECT  FISH_TYPE FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING LENGTH = MAX(LENGTH)
)
ORDER BY ID
