SELECT (SELECT SUM(SCORE) FROM HR_GRADE
            
          GROUP BY EMP_NO
         ORDER BY SUM(SCORE) DESC
         LIMIT 1) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL FROM HR_EMPLOYEES
    WHERE EMP_NO = (SELECT EMP_NO FROM HR_GRADE GROUP BY EMP_NO ORDER BY SUM(SCORE) DESC LIMIT 1)